In [8]:
from sklearn.datasets import load_iris
import pandas as pd
data = load_iris()

In [2]:
feature_names = data.keys()   # или data.feature_names
X = data.data
y = data.target

In [9]:
X = data.data
y = data.target
df_X = pd.DataFrame(X, columns=['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)'])
df_y = pd.Series(y)
X.shape

(150, 4)

In [11]:
df_y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Length: 150, dtype: int64

In [5]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [6]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

Я хочу на графике показать все эти цветки

In [15]:
import pandas as pd
import numpy as np

class MyLineReg():
    def __init__(self, n_iter=1000, learning_rate=0.001, weights=None):
        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights

    def __str__(self):
        return "MyLineReg class: n_iter={}, learning_rate={}".format(self.n_iter, self.learning_rate)
    
    def demo_fit(self, X, y, verbose=False):

        print("X до ввода нового столбца: \n", X, "\n")
        X.insert(0, "bias", 1)
        m, n = X.shape # m - кол-во строк; n - кол-во столбцов

        print("self.weights до заполнения: \n", self.weights, "\n")
        self.weights = np.ones(n) # засовывваем в эту переменную np массив со значениями 1 в кол-ве равном кол-ву переменных в одном векторе в X
        
        X_mat = X.values # Превращаем из DataFrame в np array
        y_vec = y.values
        y_pred = X_mat @ self.weights

        errors = y_pred - y_vec
        MSE = np.mean(errors**2)

        gradient = (2 / m) * (X_mat.T @ (y_pred - y_vec))
        

        print("X после ввода нового столбца: \n", X, "\n")
        print("self.weights после заполнения: \n", self.weights, "\n")
        print("X_mat: \n", X_mat, "\n")
        print("X_mat.T: \n", X_mat.T, "\n")
        print("y_vec: \n", y_vec, "\n")
        print("m, n: \n", m, n, "\n")
        print("y_pred \n", y_pred, "\n")
        print("errors \n", errors, "\n")
        print("MSE \n", MSE, "\n")
        print("gradient \n", gradient, "\n")




    def fit(self, X, y, verbose=False):
        # X.insert(0, "bias", 1)
        m, n = X.shape # m - кол-во строк; n - кол-во столбцов

        self.weights = np.ones(n) # засовывваем в эту переменную np массив со значениями 1 в кол-ве равном кол-ву переменных в одном векторе в X
        
        X_mat = X.values # Превращаем из DataFrame в np array
        y_vec = y.values
        y_pred = X_mat @ self.weights

        errors = y_pred - y_vec
        MSE = np.mean(errors**2)

        if verbose:
            print(f"start | loss: {MSE}")

        for i in range(1, self.n_iter + 1):
            y_pred = X_mat @ self.weights
            errors = y_pred - y_vec           # 🔹 ОБЯЗАТЕЛЬНО обновляем
            gradient = (2 / m) * (X_mat.T @ errors)
            self.weights = self.weights - self.learning_rate * gradient
            loss = np.mean(errors**2)         # теперь верный loss

            if verbose and i % verbose == 0:
                print(f"iter {i} | loss: {loss}")
                print(self.weights)


    def get_coef(self):
        return self.weights[1:]



verbose = 100
MyLineReg1 = MyLineReg()
print(MyLineReg1)
MyLineReg1.fit(df_X, df_y, verbose)

MyLineReg class: n_iter=1000, learning_rate=0.001
start | loss: 197.73833333333334
iter 100 | loss: 0.12810641923588106
[ 0.76693838 -0.34936246  0.27315631  0.16182589  0.73348671]
iter 200 | loss: 0.0884777731625372
[ 0.75892886 -0.36303831  0.23590397  0.20545242  0.75184721]
iter 300 | loss: 0.07144243560222728
[ 0.75349958 -0.37092081  0.21029703  0.2337351   0.76283672]
iter 400 | loss: 0.06401741380252055
[ 0.74975141 -0.37504291  0.19230314  0.25201461  0.76903616]
iter 500 | loss: 0.060683411109418536
[ 0.7470984  -0.37672841  0.1792936   0.26377404  0.77212837]
iter 600 | loss: 0.05909397867518328
[ 0.74515851 -0.3768402   0.16955418  0.27128432  0.77321027]
iter 700 | loss: 0.05825146151798196
[ 0.74368268 -0.37594065  0.16196688  0.27602607  0.77299683]
iter 800 | loss: 0.05773158687510983
[ 0.74250854 -0.37439618  0.15580244  0.27896462  0.77195395]
iter 900 | loss: 0.05735383393114785
[ 0.74153026 -0.37244549  0.15058507  0.28072935  0.77038516]
iter 1000 | loss: 0.057041